### ISSUE TITLE
Symlink /tmp/bun-node/node breaks after upgrading

### ISSUE THREAD

**Issue by feefs** [oven-sh/homebrew-bun#10]
I originally opened this issue at https://github.com/oven-sh/bun/issues/6561, but here may be a better place.

Anyone else running into the problem with the `/tmp/bun-node/node` symlink pointing to an old installation after upgrading bun? `bunx` won't recreate the symlink if it already exists, so I'm working around it by deleting it manually.

<img width="609" alt="276022498-8e08bf3e-909d-49b2-8ec7-73aeff1ada58" src="https://github.com/oven-sh/homebrew-bun/assets/25848712/0417d3e9-698c-4378-ac23-0cf0abd7957f">

Would deleting `/tmp/bun-node/node` sometime during installation be a good idea?

**Comment by Electroid** [comment]
This is indeed an issue with Bun, keeping it in #6561 is fine. Right now, Bun only sets the symlink once, but it needs to set the symlink with the current executable.
