### ISSUE TITLE
Missing capitalization in Formula folder name breaks Linuxbrew support

### ISSUE THREAD

**Issue by BurnerWah** [oven-sh/homebrew-bun#3]
Homebrew checks for a `Formula` folder in the tap.
On Linux, filesystems are usually case-sensitive, so the `formula` folder is entirely distinct from `Formula`. Both can exist at the same time.
Since this tap has a `formula` folder instead of a `Formua` folder, nothing from the tap appears on Linux.

Here's an example, including making `Formula` a symlink to `formula` to show what should happen when searching the tap.
![image](https://user-images.githubusercontent.com/10004812/200644917-7576de2d-5580-4ac2-b78d-e6208bee3261.png)

It should be able to be fixed by just renaming the `formula` folder.

**Comment by YaBoiBurner** [comment]
This might also be why all the tests are failing. (It's definitely involved in the ubuntu tests failing, less sure about macos)
